[[plugins]]
repo = 'Shougo/dein.vim'

# Let dein manage dein
# Required:
#call dein#add('$HOME/.vim/repos/github.com/Shougo/dein.vim')

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

#[[plugins]]
#repo = 'Shougo/vimshell'
#rev  = '3787e5'
